server.port: 17021
spring:
  application.name: user-service
  profiles.active: ${config.profile:test}
eureka:
  client.serviceUrl.defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    hostname: ${spring.cloud.client.ipAddress}
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
management.security.enabled: false